package app

import (
	"previous/.metagen/pageinfo"
	"previous/auth"
	. "previous/components"

	. "maragu.dev/gomponents"
	. "maragu.dev/gomponents/html"
)


func AppLayout(title string, identity auth.Identity, children ...Node) Node {
	return RootLayout(title+" | Previous",
		Body(Class("bg-neutral-50 h-full"),
			Div(Attr("x-data", "{ profileDropdownOpen: false, mobileMenuOpen: false }"), Class("min-h-full"),
				Nav(Class("bg-neutral-800"),
					Div(Class("mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"),
						Div(Class("flex h-16 items-center justify-between"),
							Div(Class("flex items-center"),
								Div(Class("flex-shrink-0"),
									A(Href(pageinfo.Root.Index.Url()), Img(Class("h-12 w-12"), Src("/images/logo.svg"), Alt("Previous"))),
								),
								Div(Attr("x-data", "{ examplesDropdownOpen: false }"), Class("hidden md:block"),
									Div(Class("ml-10 flex items-baseline space-x-4"),
										A(Href(pageinfo.Root.App.Dashboard.Url()), Class("px-3 py-2 text-sm font-medium text-neutral-100 hover:text-white"), Text("Dashboard")),
										A(Href(pageinfo.Root.App.Sitemap.Url()), Class("px-3 py-2 text-sm font-medium text-neutral-100 hover:text-white"), Text("Sitemap")),
										Div(Attr("x-on:click.outside", "examplesDropdownOpen = false"), Class("relative ml-3"),
											Div(
												Button(Attr("x-on:click", "examplesDropdownOpen = !examplesDropdownOpen;"), Class("cursor-pointer relative flex px-3 py-2 text-sm font-medium text-neutral-100 hover:text-white"), Div(Class("flex items-center"), Span(Text("Examples ")), Icon(ICON_CHEVRON_DOWN, 16))),
											),
											Div(Attr("x-cloak"), Attr("x-show", "examplesDropdownOpen"), Class("absolute right-0 z-10 mt-2 w-48 origin-top-right bg-white py-1 shadow-lg focus:outline-none"), TabIndex("-1"),
												A(Href(pageinfo.Root.App.Examples.Index.Url()), Class("block px-4 py-2 text-sm text-neutral-700 hover:bg-neutral-100"), TabIndex("-1"), Text("Example Index Page")),
												A(Href(pageinfo.Root.App.Examples.Autotable.Url()), Class("block px-4 py-2 text-sm text-neutral-700 hover:bg-neutral-100"), TabIndex("-1"), Text("Auto Table")),
												A(Href(pageinfo.Root.App.Examples.Forms.Url()), Class("block px-4 py-2 text-sm text-neutral-700 hover:bg-neutral-100"), TabIndex("-1"), Text("Form Submission")),
												A(Href(pageinfo.Root.App.Examples.Htmx.Url()), Class("block px-4 py-2 text-sm text-neutral-700 hover:bg-neutral-100"), TabIndex("-1"), Text("HTMX")),
												A(Href(pageinfo.Root.App.Examples.Alpine.Url()), Class("block px-4 py-2 text-sm text-neutral-700 hover:bg-neutral-100"), TabIndex("-1"), Text("Alpine.js")),
												A(Href(pageinfo.Root.App.Examples.Ui_playground.Url()), Class("block px-4 py-2 text-sm text-neutral-700 hover:bg-neutral-100"), TabIndex("-1"), Text("UI Elements")),
												A(Href(pageinfo.Root.App.Examples.Upload.Url()), Class("block px-4 py-2 text-sm text-neutral-700 hover:bg-neutral-100"), TabIndex("-1"), Text("File Uploading")),
												A(Href(pageinfo.Root.App.Examples.Smtp.Url()), Class("block px-4 py-2 text-sm text-neutral-700 hover:bg-neutral-100"), TabIndex("-1"), Text("SMTP Client")),
												A(Href(pageinfo.Root.App.Examples.Markdown.Url()), Class("block px-4 py-2 text-sm text-neutral-700 hover:bg-neutral-100"), TabIndex("-1"), Text("Markdown Rendering")),
												A(Href(pageinfo.Root.App.Examples.Api_fetch.Url()), Class("block px-4 py-2 text-sm text-neutral-700 hover:bg-neutral-100"), TabIndex("-1"), Text("Server-side API Fetch")),
											),
										),
										A(Href("https://github.com/maxamundsen/Previous/wiki"), Target("_blank"), Class("px-3 py-2 text-sm font-medium text-neutral-100 hover:text-white"), Text("Documentation")),
									),
								),
								Template(),
							),
							Div(Class("hidden md:block"),
								Div(Class("ml-4 flex items-center md:ml-6"),
									Div(Class("relative ml-3"),
										Div(
											Button(Attr("x-on:click", "profileDropdownOpen = !profileDropdownOpen"), Attr("x-on:click.outside", "profileDropdownOpen = false"), Type("button"), Class("cursor-pointer relative flex max-w-xs items-center bg-neutral-800 text-sm focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-neutral-800"),
												Span(Class("absolute -inset-1.5")),
												Span(Class("sr-only"), Text("Open user menu")),
												Img(Class("h-8 w-8 rounded-full"), Src("/images/profile_picture.png"), Alt("profile picture")),
											),
										),
										Div(Attr("x-cloak"), Attr("x-show", "profileDropdownOpen"), Class("absolute right-0 z-10 mt-2 w-48 origin-top-right bg-white py-1 shadow-lg focus:outline-none"), TabIndex("-1"),
											A(Href(pageinfo.Root.App.Account.Url()), Class("block px-4 py-2 text-sm text-neutral-700 hover:bg-neutral-100"), TabIndex("-1"), ID("user-menu-item-0"), Text("Your Profile")),
											A(Href(pageinfo.Root.Auth.Logout.Url()), Class("block px-4 py-2 text-sm text-neutral-700 hover:bg-neutral-100"), TabIndex("-1"), ID("user-menu-item-2"), Text("Log out")),
										),
									),
								),
							),
							Div(Class("-mr-2 flex md:hidden"),
								Button(Attr("x-on:click", "mobileMenuOpen = !mobileMenuOpen"), Type("button"), Class("relative inline-flex items-center justify-center p-2 text-neutral-400 hover:bg-neutral-900 hover:text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-neutral-800"),
									Span(Class("absolute -inset-0.5")),
									Span(Class("sr-only"), Text("Open main menu")),
									Icon(ICON_MENU, 24),
								),
							),
						),
					),
					Div(Attr("x-show", "mobileMenuOpen"), Attr("x-on:click.outside", "mobileMenuOpen = false"), Attr("x-cloak"), Class("md:hidden"),
						Div(Class("space-y-1 px-2 pb-3 pt-2 sm:px-3"),
							A(Href(pageinfo.Root.App.Dashboard.Url()), Class("block hover:bg-neutral-900 px-3 py-2 text-base font-medium text-white"), Text("Dashboard")),
						),
						Div(Class("border-t border-neutral-700 pb-3 pt-4"),
							Div(Class("flex items-center px-5"),
								Div(Class("flex-shrink-0"),
									Img(Class("h-10 w-10 rounded-full"), Src("/images/profile_picture.png"), Alt("profile picture")),
								),
								Div(Class("ml-3"),
									Div(Class("text-base/5 font-medium text-white"), Text(identity.User.Firstname+" "+identity.User.Lastname)),
									Div(Class("text-sm font-medium text-neutral-400"), Text(identity.User.Email)),
								),
							),
							Div(Class("mt-3 space-y-1 px-2"),
								A(Href(pageinfo.Root.Api.Account.Url()), Class("block px-3 py-2 text-base font-medium text-neutral-200 hover:bg-neutral-900 hover:text-white"), Text("Your Profile")),
								A(Href(pageinfo.Root.Auth.Logout.Url()), Class("block px-3 py-2 text-base font-medium text-neutral-200 hover:bg-neutral-900 hover:text-white"), Text("Log out")),
							),
						),
					),
				),
				Header(Class("bg-white shadow"),
					Div(Class("mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8"),
						H1(Class("text-3xl font-bold tracking-tight text-neutral-950"), Text(title)),
					),
				),
				Main(
					Div(Class("mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8"),
						Group(children),
					),
				),
			),
		),
	)
}
