package components

import (
	. "maragu.dev/gomponents"
	. "maragu.dev/gomponents/html"
	"webdawgengine/models"
)

func AppLayout(title string, identity models.Identity, children ...Node) Node {
	return Root(title+" | WebDawgEngine",
		Body(Attr("hx-boost", "true"), Class("bg-gray-50 h-full"),
			Div(Attr("x-data", "{ profileDropdownOpen: false, mobileMenuOpen: false }"), Class("min-h-full"),
				Nav(Class("bg-red-800"),
					Div(Class("mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"),
						Div(Class("flex h-16 items-center justify-between"),
							Div(Class("flex items-center"),
								Div(Class("flex-shrink-0"),
									A(Href("/"), Img(Class("h-8 w-8"), Src("/images/logo_white.svg"), Alt("WebDawgEngine"))),
								),
								Div(Attr("x-data", "{ examplesDropdownOpen: false }"), Class("hidden md:block"),
									Div(Class("ml-10 flex items-baseline space-x-4"),
										A(Href("/app/dashboard"), Class("rounded-md px-3 py-2 text-sm font-medium text-gray-50 hover:bg-red-700 hover:text-white"), Text("Dashboard")),
										Div(Class("relative ml-3"),
											Div(
												Button(Attr("x-on:click", "examplesDropdownOpen = !examplesDropdownOpen;"), Attr("x-on:click.outside", "examplesDropdownOpen = false"), Class("relative flex rounded-md px-3 py-2 text-sm font-medium text-gray-50 hover:bg-red-700 hover:text-white"), Div(Class("flex items-center"), Span(Text("Examples ")), Icon("chevron-down", 16))),
											),
											Div(Attr("x-cloak"), Attr("x-show", "examplesDropdownOpen"), Class("absolute right-0 z-10 mt-2 w-48 origin-top-right rounded-md bg-white py-1 shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none"), TabIndex("-1"),
												A(Href("/app/examples/htmx"), Class("block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"), TabIndex("-1"), Text("HTMX")),
												A(Href("/app/examples/alpine"), Class("block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"), TabIndex("-1"), Text("Alpine.js")),
												A(Href("/app/examples/upload"), Class("block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"), TabIndex("-1"), Text("File Uploading")),
												A(Href("/app/examples/smtp"), Class("block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"), TabIndex("-1"), Text("SMTP Client")),
												A(Href("/app/examples/api-fetch"), Class("block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"), TabIndex("-1"), Text("Server-side API Fetch")),
											),
										),
										A(Href("/app/api-demo"), Class("rounded-md px-3 py-2 text-sm font-medium text-gray-50 hover:bg-red-700 hover:text-white"), Text("API Demo")),
									),
								),
							),
							Div(Class("hidden md:block"),
								Div(Class("ml-4 flex items-center md:ml-6"),
									Div(Class("relative ml-3"),
										Div(
											Button(Attr("x-on:click", "profileDropdownOpen = !profileDropdownOpen"), Attr("x-on:click.outside", "profileDropdownOpen = false"), Type("button"), Class("relative flex max-w-xs items-center rounded-full bg-gray-800 text-sm focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800"),
												Span(Class("absolute -inset-1.5")),
												Span(Class("sr-only"), Text("Open user menu")),
												Img(Class("h-8 w-8 rounded-full"), Src("/images/profile_picture.png"), Alt("profile picture")),
											),
										),
										Div(Attr("x-cloak"), Attr("x-show", "profileDropdownOpen"), Class("absolute right-0 z-10 mt-2 w-48 origin-top-right rounded-md bg-white py-1 shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none"), TabIndex("-1"),
											A(Href("/app/account"), Class("block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"), TabIndex("-1"), ID("user-menu-item-0"), Text("Your Profile")),
											A(Attr("hx-boost", "false"), Href("/docs"), Class("block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"), TabIndex("-1"), ID("user-menu-item-0"), Text("Documentation")),
											A(Attr("hx-boost", "false"), Href("/auth/logout"), Class("block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"), TabIndex("-1"), ID("user-menu-item-2"), Text("Log out")),
										),
									),
								),
							),
							Div(Class("-mr-2 flex md:hidden"),
								Button(Attr("x-on:click", "mobileMenuOpen = !mobileMenuOpen"), Type("button"), Class("relative inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-red-600 hover:text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800"),
									Span(Class("absolute -inset-0.5")),
									Span(Class("sr-only"), Text("Open main menu")),
									Icon("menu", 24),
								),
							),
						),
					),
					Div(Attr("x-show", "mobileMenuOpen"), Attr("x-on:click.outside", "mobileMenuOpen = false"), Attr("x-cloak"), Class("md:hidden"),
						Div(Class("space-y-1 px-2 pb-3 pt-2 sm:px-3"),
							A(Href("/app/dashboard"), Class("block rounded-md hover:bg-red-600 px-3 py-2 text-base font-medium text-white"), Text("Dashboard")),
						),
						Div(Class("border-t border-gray-700 pb-3 pt-4"),
							Div(Class("flex items-center px-5"),
								Div(Class("flex-shrink-0"),
									Img(Class("h-10 w-10 rounded-full"), Src("/images/profile_picture.png"), Alt("profile picture")),
								),
								Div(Class("ml-3"),
									Div(Class("text-base/5 font-medium text-white"), Text(identity.User.Firstname+" "+identity.User.Lastname)),
									Div(Class("text-sm font-medium text-gray-400"), Text(identity.User.Email)),
								),
							),
							Div(Class("mt-3 space-y-1 px-2"),
								A(Href("/app/account"), Class("block rounded-md px-3 py-2 text-base font-medium text-gray-200 hover:bg-red-600 hover:text-white"), Text("Your Profile")),
								A(Attr("hx-boost", "false"), Href("/auth/logout"), Class("block rounded-md px-3 py-2 text-base font-medium text-gray-200 hover:bg-red-600 hover:text-white"), Text("Log out")),
							),
						),
					),
				),
				Header(Class("bg-white shadow"),
					Div(Class("mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8"),
						H1(Class("text-3xl font-bold tracking-tight text-gray-900"), Text(title)),
					),
				),
				Main(
					Div(Class("mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8"),
						Group(children),
					),
				),
			),
		),
	)
}
