// @Metagen -- THIS FILE WAS AUTOGENERATED BY METAGEN - DO NOT EDIT BY HAND
package main

import (
	"net/http"
	"saral/middleware"
	"saral/pages/api"
	"saral/pages/app"
	"saral/pages/app/examples"
	"saral/pages/auth"
)

func mapAutoRoutes(mux *http.ServeMux) {
	mux.HandleFunc("/api/account", middleware.LoadIdentity(api.AccountController, true))
	mux.HandleFunc("/api/auth", middleware.LoadIdentity(api.LoginController, false))
	mux.HandleFunc("/api/test", middleware.LoadIdentity(middleware.LoadSessionFromCookie(api.TestController), true))
	mux.HandleFunc("/app/account", middleware.LoadIdentity(middleware.LoadSessionFromCookie(app.AccountController), true))
	mux.HandleFunc("/app/api-demo", middleware.LoadIdentity(middleware.LoadSessionFromCookie(app.ApiDemoController), true))
	mux.HandleFunc("/app/dashboard", middleware.LoadIdentity(middleware.LoadSessionFromCookie(app.DashboardController), true))
	mux.HandleFunc("/app/examples/alpine", middleware.LoadIdentity(middleware.LoadSessionFromCookie(examples.AlpineController), true))
	mux.HandleFunc("/app/examples/api-fetch", middleware.LoadIdentity(middleware.LoadSessionFromCookie(examples.ApiFetchController), true))
	mux.HandleFunc("/app/examples/forms", middleware.LoadIdentity(examples.FormController, true))
	mux.HandleFunc("/app/examples/htmx", middleware.LoadIdentity(middleware.LoadSessionFromCookie(examples.HtmxController), true))
	mux.HandleFunc("/app/examples/smtp", middleware.LoadIdentity(middleware.LoadSessionFromCookie(examples.SmtpController), true))
	mux.HandleFunc("/app/examples/upload", middleware.LoadIdentity(middleware.LoadSessionFromCookie(examples.UploadController), true))
	mux.HandleFunc("/auth/login", middleware.LoadIdentity(middleware.LoadSessionFromCookie(auth.LoginController), false))
	mux.HandleFunc("/auth/logout", middleware.LoadIdentity(middleware.LoadSessionFromCookie(auth.LogoutController), true))
}
