package examples

import (
	"previous/.jet/model"
	"previous/.jet/table"

	. "previous/components"

	"github.com/go-jet/jet/v2/sqlite"

	. "maragu.dev/gomponents"
	. "maragu.dev/gomponents/html"

	"previous/repository"

	"net/http"
)

func AutoTableHxPage(w http.ResponseWriter, r *http.Request) {
	filter := repository.ParseFilterFromRequest(r)
	filter.Pagination.Enabled = true

	// fetch entities from filter function
	// this first counts the possible items before pagination
	searchItems, _ := repository.OrderRepository{}.Filter(repository.Filter{Search: filter.Search})

	// this query gets the data AFTER pagination
	orders, _ := repository.OrderRepository{}.Filter(filter)

	// generate page numbers according to total length of data
	filter.Pagination.GeneratePagination(len(searchItems), len(orders))

	// You can automatically generate friendly names from the SQL columns:
	cols := repository.GetColInfoFromJet(
		sqlite.ColumnList{
			table.Order.ID,
			table.Order.ProductID,
			table.Order.PurchaserName,
			table.Order.PurchaserEmail,
			table.Order.Price,
		},
	)

	// You can even grab EVERY column
	// Keep in mind the ordering of the columns is determined by the struct ordering (which is generated by jet at comptime)
	cols = repository.GetColInfoFromJet(table.Order.AllColumns)

	// Or you can map them manually:
	cols = []repository.ColInfo{
		{DbName: table.Order.ID.Name(), DisplayName: "ID"},
		{DbName: table.Order.ProductID.Name(), DisplayName: "Product ID"},
		{DbName: table.Order.PurchaserName.Name(), DisplayName: "Customer", Sortable: true},
		{DbName: table.Order.PurchaserEmail.Name(), DisplayName: "Customer Email", Sortable: true},
		{DbName: table.Order.Price.Name(), DisplayName: "Price (USD)", Sortable: true},
	}

	// Generate HTML
	func() Node {
		elId := "order_table"
		return AutoTable(
			elId,
			r.URL.Path,
			cols,
			filter,
			orders,
			AutotableSearchGroup(
				AutotableSearch(
					Placeholder("Search Customer Name..."),
					BindSearch(elId, table.Order.PurchaserName.Name()),
					AutoFocus(),
				),
				AutotableSearch(
					Placeholder("Search Customer Email..."),
					BindSearch(elId, table.Order.PurchaserEmail.Name()),
					AutoFocus(),
				),
				AutotableSearch(
					Placeholder("Price Min"),
					BindSearch(elId, table.Order.Price.Name()+"_left"),
				),
				AutotableSearch(
					Placeholder("Price Max"),
					BindSearch(elId, table.Order.Price.Name()+"_right"),
				),
			),
			func(order model.Order) Node {
				return AutotableRow(
					AutotableItemBold(ToText(order.ID)),
					AutotableItem(ToText(order.ProductID)),
					AutotableItem(ToText(order.PurchaserName)),
					AutotableItem(ToText(order.PurchaserEmail)),
					AutotableItemBold(Text("$"), FormatMoney(int64(order.Price))),
				)
			},
			nil,
		)
	}().Render(w)
}
