package main

import (
	"fmt"
	"log"
	"net/http"
	"previous/config"
	"previous/pages"
	"previous/repository"
	"previous/tasks"
)

// Entry point for the application, initializes package globals
// such as the database connections, http multiplexer, config, etc.
func main() {
	fmt.Println("Previous: A simple web codebase.\n")

	if config.DEBUG {
		fmt.Println("DEBUG BUILD")
	} else {
		fmt.Println("RELEASE BUILD")
	}

	config.LoadConfig()

	repository.Init()

	// create http multiplexer, map routes
	mux := http.NewServeMux()

	pages.Init()

	mapAutoRoutes(mux) // function autogenerated by Metagen
	mapManualRoutes(mux)

	// Task Scheduler
	tasks.InitTasks()

	log.Println("Mapped HTTP routes")

	log.Println("Listening on http://" + config.GetConfig().Host + ":" + config.GetConfig().Port)

	serveErr := http.ListenAndServe(config.GetConfig().Host+":"+config.GetConfig().Port, mux)

	if serveErr != nil {
		log.Fatal(serveErr)
	}
}
